version: '2'

networks:
  auth:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
          gateway: 172.0.0.1

services:
  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: ${MEDIARATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MEDIARATE_POSTGRES_PASSWORD}
      POSTGRES_DB: mediarate
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgres
    networks:
      auth:
        ipv4_address: 172.0.0.10
    ports:
      - '5432'

  mediarate:
    build: .
    environment:
      POSTGRES_USER: ${MEDIARATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MEDIARATE_POSTGRES_PASSWORD}
      DB_NAME: mediarate
      DB_HOST: 172.0.0.10
    restart: always
    networks:
      auth:
        ipv4_address: 172.0.0.20
    ports:
      - '8080'